export interface Product {
  id: string;
  name: string;
  category: 'hoodies' | 'tshirts' | 'shirts' | 'pants';
  price: number;
  description: string;
  images: string[];
  sizes: string[];
  features?: string[]; // Optional product features
}

export const products: Product[] = [
  // Hoodies
  {
    id: 'hoodie-1',
    name: 'Худи "Азъ"',
    category: 'hoodies',
    price: 6990,
    description: 'Классическое худи с принтом первой буквы древнерусского алфавита. Символизирует начало пути и самопознание.',
    images: ['https://images.unsplash.com/photo-1762575910569-46971cd69df3?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxzdHJlZXR3ZWFyJTIwZmFzaGlvbiUyMG1vZGVsJTIwaG9vZGllfGVufDF8fHx8MTc2MzA0NDYzNnww&ixlib=rb-4.1.0&q=80&w=1080'],
    sizes: ['S', 'M', 'L', 'XL', 'XXL'],
    features: ['100% хлопок', 'Оверсайз крой', 'Принт высокого качества', 'Двойной капюшон'],
  },
  {
    id: 'hoodie-2',
    name: 'Худи "Наследие"',
    category: 'hoodies',
    price: 7490,
    description: 'Премиум худи с вышивкой на груди и спине. Отражает связь поколений и силу традиций.',
    images: ['https://images.unsplash.com/photo-1619289398204-2e90bf1722e9?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHx1cmJhbiUyMGZhc2hpb24lMjBibGFjayUyMGJhY2tncm91bmR8ZW58MXx8fHwxNzYzMDQ0NjM2fDA&ixlib=rb-4.1.0&q=80&w=1080'],
    sizes: ['S', 'M', 'L', 'XL', 'XXL'],
    features: ['Премиум хлопок', 'Вышивка золотой нитью', 'Утепленная версия', 'Карман кенгуру'],
  },
  {
    id: 'hoodie-3',
    name: 'Худи "Единство"',
    category: 'hoodies',
    price: 6490,
    description: 'Минималистичное худи с акцентом на чистоту линий и форм.',
    images: ['https://images.unsplash.com/photo-1507297448044-a99b358cd06e?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxtaW5pbWFsJTIwZmFzaGlvbiUyMGNsb3RoaW5nfGVufDF8fHx8MTc2MzAxMjQ1M3ww&ixlib=rb-4.1.0&q=80&w=1080'],
    sizes: ['S', 'M', 'L', 'XL', 'XXL'],
    features: ['Плотный хлопок', 'Минималистичный дизайн', 'Удлиненный крой', 'Рибаная резинка'],
  },
  {
    id: 'hoodie-4',
    name: 'Худи "Сила"',
    category: 'hoodies',
    price: 7990,
    description: 'Худи с мощным графическим принтом, отражающим внутреннюю силу и непоколебимость.',
    images: ['https://images.unsplash.com/photo-1762575910569-46971cd69df3?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxzdHJlZXR3ZWFyJTIwZmFzaGlvbiUyMG1vZGVsJTIwaG9vZGllfGVufDF8fHx8MTc2MzA0NDYzNnww&ixlib=rb-4.1.0&q=80&w=1080'],
    sizes: ['S', 'M', 'L', 'XL', 'XXL'],
    features: ['Премиум ткань', 'Яркий принт', 'Укрепленные швы', 'Капюшон с кулисой'],
  },
  {
    id: 'hoodie-5',
    name: 'Худи "Корни"',
    category: 'hoodies',
    price: 6790,
    description: 'Худи, символизирующее глубокую связь с историческими корнями.',
    images: ['https://images.unsplash.com/photo-1619289398204-2e90bf1722e9?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHx1cmJhbiUyMGZhc2hpb24lMjBibGFjayUyMGJhY2tncm91bmR8ZW58MXx8fHwxNzYzMDQ0NjM2fDA&ixlib=rb-4.1.0&q=80&w=1080'],
    sizes: ['S', 'M', 'L', 'XL', 'XXL'],
    features: ['Мягкий хлопок', 'Винтажная обработка', 'Принт на спине', 'Широкие манжеты'],
  },
  {
    id: 'hoodie-6',
    name: 'Худи "Путь"',
    category: 'hoodies',
    price: 7290,
    description: 'Худи для тех, кто идет своим путем и не боится быть собой.',
    images: ['https://images.unsplash.com/photo-1507297448044-a99b358cd06e?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxtaW5pbWFsJTIwZmFzaGlvbiUyMGNsb3RoaW5nfGVufDF8fHx8MTc2MzAxMjQ1M3ww&ixlib=rb-4.1.0&q=80&w=1080'],
    sizes: ['S', 'M', 'L', 'XL', 'XXL'],
    features: ['Органический хлопок', 'Эко-печать', 'Регулируемый капюшон', 'Боковые карманы'],
  },

  // T-Shirts
  {
    id: 'tshirt-1',
    name: 'Футболка "Буквица"',
    category: 'tshirts',
    price: 2990,
    description: 'Базовая футболка с элементами древнерусской письменности.',
    images: ['https://images.unsplash.com/photo-1761637332438-02a9319195f8?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxzdHJlZXR3ZWFyJTIwdHNoaXJ0JTIwbW9kZWx8ZW58MXx8fHwxNzYzMDQ0NjM3fDA&ixlib=rb-4.1.0&q=80&w=1080'],
    sizes: ['S', 'M', 'L', 'XL', 'XXL'],
    features: ['100% хлопок', 'Плотность 180 г/м²', 'Оверсайз крой', 'Принт на груди'],
  },
  {
    id: 'tshirt-2',
    name: 'Футболка "Держава"',
    category: 'tshirts',
    price: 3490,
    description: 'Футболка с символикой силы и величия.',
    images: ['https://images.unsplash.com/photo-1761637332438-02a9319195f8?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxzdHJlZXR3ZWFyJTIwdHNoaXJ0JTIwbW9kZWx8ZW58MXx8fHwxNzYzMDQ0NjM3fDA&ixlib=rb-4.1.0&q=80&w=1080'],
    sizes: ['S', 'M', 'L', 'XL', 'XXL'],
    features: ['Премиум хлопок', 'Двойная прострочка', 'Золотой принт', 'Усиленный ворот'],
  },
  {
    id: 'tshirt-3',
    name: 'Футболка "Русь"',
    category: 'tshirts',
    price: 2790,
    description: 'Минималистичная футболка с акцентом на идентичность.',
    images: ['https://images.unsplash.com/photo-1761637332438-02a9319195f8?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxzdHJlZXR3ZWFyJTIwdHNoaXJ0JTIwbW9kZWx8ZW58MXx8fHwxNzYzMDQ0NjM3fDA&ixlib=rb-4.1.0&q=80&w=1080'],
    sizes: ['S', 'M', 'L', 'XL', 'XXL'],
    features: ['Мягкий хлопок', 'Классический крой', 'Малый принт', 'Долговечная печать'],
  },
  {
    id: 'tshirt-4',
    name: 'Футболка "Память"',
    category: 'tshirts',
    price: 3290,
    description: 'Футболка, хранящая память о великом прошлом.',
    images: ['https://images.unsplash.com/photo-1761637332438-02a9319195f8?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxzdHJlZXR3ZWFyJTIwdHNoaXJ0JTIwbW9kZWx8ZW58MXx8fHwxNzYzMDQ0NjM3fDA&ixlib=rb-4.1.0&q=80&w=1080'],
    sizes: ['S', 'M', 'L', 'XL', 'XXL'],
    features: ['Органический хлопок', 'Винтажная печать', 'Свободный крой', 'Мягкая текстура'],
  },
  {
    id: 'tshirt-5',
    name: 'Футболка "Вера"',
    category: 'tshirts',
    price: 2990,
    description: 'Футболка с символами веры и духовности.',
    images: ['https://images.unsplash.com/photo-1761637332438-02a9319195f8?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxzdHJlZXR3ZWFyJTIwdHNoaXJ0JTIwbW9kZWx8ZW58MXx8fHwxNzYzMDQ0NjM3fDA&ixlib=rb-4.1.0&q=80&w=1080'],
    sizes: ['S', 'M', 'L', 'XL', 'XXL'],
    features: ['Плотный хлопок', 'Цветной принт', 'Рибаный ворот', 'Удобная посадка'],
  },
  {
    id: 'tshirt-6',
    name: 'Футболка "Культура"',
    category: 'tshirts',
    price: 3190,
    description: 'Футболка, отражающая богатство русской культуры.',
    images: ['https://images.unsplash.com/photo-1761637332438-02a9319195f8?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxzdHJlZXR3ZWFyJTIwdHNoaXJ0JTIwbW9kZWx8ZW58MXx8fHwxNzYzMDQ0NjM3fDA&ixlib=rb-4.1.0&q=80&w=1080'],
    sizes: ['S', 'M', 'L', 'XL', 'XXL'],
    features: ['Качественный хлопок', 'Детальный принт', 'Современный крой', 'Стойкая краска'],
  },

  // Shirts
  {
    id: 'shirt-1',
    name: 'Рубашка "Традиция"',
    category: 'shirts',
    price: 5990,
    description: 'Рубашка с элементами традиционного кроя и современного дизайна.',
    images: ['https://images.unsplash.com/photo-1693666342042-ed3ae05f382c?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxmYXNoaW9uJTIwc2hpcnQlMjBzdHlsaW5nfGVufDF8fHx8MTc2MzA0NDYzN3ww&ixlib=rb-4.1.0&q=80&w=1080'],
    sizes: ['S', 'M', 'L', 'XL', 'XXL'],
    features: ['Натуральный лен', 'Классический воротник', 'Пуговицы из дерева', 'Свободный крой'],
  },
  {
    id: 'shirt-2',
    name: 'Рубашка "Летопись"',
    category: 'shirts',
    price: 6490,
    description: 'Премиум рубашка с отсылками к древнерусским орнаментам.',
    images: ['https://images.unsplash.com/photo-1693666342042-ed3ae05f382c?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxmYXNoaW9uJTIwc2hpcnQlMjBzdHlsaW5nfGVufDF8fHx8MTc2MzA0NDYzN3ww&ixlib=rb-4.1.0&q=80&w=1080'],
    sizes: ['S', 'M', 'L', 'XL', 'XXL'],
    features: ['Премиум хлопок', 'Вышивка на манжетах', 'Золотые детали', 'Приталенный крой'],
  },
  {
    id: 'shirt-3',
    name: 'Рубашка "Простор"',
    category: 'shirts',
    price: 5490,
    description: 'Легкая летняя рубашка для городских прогулок.',
    images: ['https://images.unsplash.com/photo-1693666342042-ed3ae05f382c?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxmYXNoaW9uJTIwc2hpcnQlMjBzdHlsaW5nfGVufDF8fHx8MTc2MzA0NDYzN3ww&ixlib=rb-4.1.0&q=80&w=1080'],
    sizes: ['S', 'M', 'L', 'XL', 'XXL'],
    features: ['Легкий хлопок', 'Воротник стойка', 'Скрытая планка', 'Дышащая ткань'],
  },
  {
    id: 'shirt-4',
    name: 'Рубашка "Воевода"',
    category: 'shirts',
    price: 6990,
    description: 'Рубашка в темных тонах с акцентом на силу характера.',
    images: ['https://images.unsplash.com/photo-1693666342042-ed3ae05f382c?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxmYXNoaW9uJTIwc2hpcnQlMjBzdHlsaW5nfGVufDF8fHx8MTc2MzA0NDYzN3ww&ixlib=rb-4.1.0&q=80&w=1080'],
    sizes: ['S', 'M', 'L', 'XL', 'XXL'],
    features: ['Плотная ткань', 'Усиленные швы', 'Контрастные детали', 'Оверсайз'],
  },
  {
    id: 'shirt-5',
    name: 'Рубашка "Знамя"',
    category: 'shirts',
    price: 5790,
    description: 'Рубашка с символическими элементами на груди.',
    images: ['https://images.unsplash.com/photo-1693666342042-ed3ae05f382c?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxmYXNoaW9uJTIwc2hpcnQlMjBzdHlsaW5nfGVufDF8fHx8MTc2MzA0NDYzN3ww&ixlib=rb-4.1.0&q=80&w=1080'],
    sizes: ['S', 'M', 'L', 'XL', 'XXL'],
    features: ['Смесовая ткань', 'Нашивка на груди', 'Классический воротник', 'Прямой крой'],
  },
  {
    id: 'shirt-6',
    name: 'Рубашка "Богатырь"',
    category: 'shirts',
    price: 6290,
    description: 'Мощная рубашка для современных богатырей.',
    images: ['https://images.unsplash.com/photo-1693666342042-ed3ae05f382c?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxmYXNoaW9uJTIwc2hpcnQlMjBzdHlsaW5nfGVufDF8fHx8MTc2MzA0NDYzN3ww&ixlib=rb-4.1.0&q=80&w=1080'],
    sizes: ['S', 'M', 'L', 'XL', 'XXL'],
    features: ['Плотный хлопок', 'Широкие плечи', 'Усиленные пуговицы', 'Комфортный крой'],
  },

  // Pants
  {
    id: 'pants-1',
    name: 'Карго "Дружина"',
    category: 'pants',
    price: 7990,
    description: 'Функциональные брюки карго с множеством карманов.',
    images: ['https://images.unsplash.com/photo-1570467687769-18d7ba9d9734?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHx1cmJhbiUyMHBhbnRzJTIwZmFzaGlvbnxlbnwxfHx8fDE3NjMwNDQ2Mzd8MA&ixlib=rb-4.1.0&q=80&w=1080'],
    sizes: ['S', 'M', 'L', 'XL', 'XXL'],
    features: ['Прочная ткань', '8 карманов', 'Регулировка на поясе', 'Усиленные колени'],
  },
  {
    id: 'pants-2',
    name: 'Джоггеры "Странник"',
    category: 'pants',
    price: 5990,
    description: 'Комфортные джоггеры для городской жизни.',
    images: ['https://images.unsplash.com/photo-1570467687769-18d7ba9d9734?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHx1cmJhbiUyMHBhbnRzJTIwZmFzaGlvbnxlbnwxfHx8fDE3NjMwNDQ2Mzd8MA&ixlib=rb-4.1.0&q=80&w=1080'],
    sizes: ['S', 'M', 'L', 'XL', 'XXL'],
    features: ['Хлопок с эластаном', 'Резинка на манжетах', 'Глубокие карманы', 'Шнурок на поясе'],
  },
];